import streamlit as st
from utils import st_def

st.set_page_config(page_title='👋 AI SQL',  page_icon="🚀",)
st.title('🔍 AI - SQL')
st_def.st_logo()
#------------------------------------------------------------------------------------------------
st.write('''
## Entity-relationship model diagram

The image below shows an overview of the Pagila database tables and views, generated by DBeaver.

For example, the film table has string columns like title and description. It also relates to the table language with the columns language_id and original_language_id. With that information, you know that you can join both tables to get the language of each film, or to list all films for a specific language.

#### Sample queries
- List all the films by ordered by their length
- List how many films there are in each film category
- Show the actors and actresses ordered by how many movies they are featured in
- Get a list of all active customers, ordered by their first name

#### Challenge
- What is the total revenue of each rental store?
- Can you list the top 5 film genres by their gross revenue?
- The film.description has the text type, allowing for full text search queries, what will you search for?        
         
         ''')

st.error("DON'T TRY: purge or similar ones")

st.image('./images/postgresql.png')